### ISSUE TITLE
pure - AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by rschitz** [kuhn-ruess/Checkmk-Checks#56]
In the 1.4 version i got this issue at the end of the script exec:

`<<<pure_arraycertificates>>>
Traceback (most recent call last):
  File "/omd/sites/xxx/local/share/check_mk/agents/special/agent_pure", line 212, in <module>
    get_arraycertificates()
  File "/omd/sites/xxx/local/share/check_mk/agents/special/agent_pure", line 198, in get_arraycertificates
    print(f"{certificate['name']} {certificate['common_name']} {certificate['status']} {certificate['valid_from']} {certificate['valid_to']} {certificate['organizational_unit'].replace(' ','_')}|{certificate['organization'].replace(' ','_')}")
AttributeError: 'NoneType' object has no attribute 'replace'
`

**Comment by bsplesnialy** [comment]
Same for version 1.4.1, tested right now
![obraz](https://github.com/kuhn-ruess/Checkmk-Checks/assets/138007472/382023b1-0aed-4d35-859e-28534875c1eb)

**Comment by Bastian-Kuhn** [comment]
Hello,

It seems you checking a Certificate which as missing the organization field? That's not usual, are you certain that certificate is right?

**Comment by bsplesnialy** [comment]
> 

Hi,

Actually you are right, I need to regenerate CA. But why doesn't the plugin work with incomplete CA, shouldn't it show something like a critical service instead of not working at all? For now im using version 1.3.1 but I have been following all your versions so I know that in 1.4 you have implemented CA checking.

![obraz](https://github.com/kuhn-ruess/Checkmk-Checks/assets/138007472/3d385fc7-ac50-4c0c-8d56-56b35303e202)


Sincerely,

**Comment by Bastian-Kuhn** [comment]
I pushed a 1.4.1, can you check if this fixes your problem?
Thanks in advance

**Comment by bsplesnialy** [comment]
In 1.4.1 this issue persists as I said in my 1st comment. At the moment I have tested again and nothing has changed, I need to replace the CA to check again. When I do, I will let you know in this thread.

![obraz](https://github.com/kuhn-ruess/Checkmk-Checks/assets/138007472/ca0c49ab-8f42-4f62-9c90-1685a392d9c5)

**Comment by Bastian-Kuhn** [comment]
Cant be the same error, the code line there is now diffrent? Can you send the new trace

**Comment by bsplesnialy** [comment]
Agent exited with code 1: Traceback (most recent call last):
File "/omd/sites/^site^/local/share/check_mk/agents/special/agent_pure", line 212, in <module>
get_arraycertificates()
File "/omd/sites/^site^/local/share/check_mk/agents/special/agent_pure", line 198, in get_arraycertificates
print(f"{certificate['name']} {certificate['common_name']} {certificate['status']} {certificate['valid_from']} {certificate['valid_to']} {certificate['organizational_unit'].replace(' ','_')}|{certificate['organization'].replace(' ','_')}")
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by Bastian-Kuhn** [comment]
So sorry, the Push was not working, should be 1.4.2 not 1.4.1
